allow-lan: true
external-controller: 127.0.0.1:9090
log-level: info
mode: rule
port: 7890
proxies: []
proxy-groups:
- name: ๐ ่็น้ๆฉ
  proxies:
  - โป๏ธ ่ชๅจ้ๆฉ
  - DIRECT
  type: select
- interval: 300
  name: โป๏ธ ่ชๅจ้ๆฉ
  proxies:
  - DIRECT
  type: url-test
  url: http://www.gstatic.com/generate_204
redir-port: 7892
rules:
- DOMAIN-SUFFIX,local,DIRECT
- DOMAIN-SUFFIX,qq.com,DIRECT
- DOMAIN-SUFFIX,google.com,๐ ่็น้ๆฉ
- GEOIP,CN,DIRECT
- MATCH,๐ ่็น้ๆฉ
socks-port: 7891
